### ISSUE TITLE
Failed to initialize graphics - running wine and steam

### ISSUE THREAD

**Issue by beatc1234** [oh-nyoo/steam-deck-advance#1]
Hi, i have a problem running non steam game via wine in gaming mode. It shows an error "Failed to initialize graphics" when I started up the game, It plays well in desktop mode tho. Any additional cmd should i put into the LAUNCH OPTIONS?

**Comment by oh-nyoo** [comment]
I can't say I've experienced this myself unfortunately, but I have read there may be some issues with games running Vulkan when using gaming mode. There may be additional commands you could put into launch options that will allow you to force it to use OpenGL, but that would depend on your game.

Also if you are on the beta branch for the Steam Deck, I would go back to stable.

If all that doesn't help, you could try using bottles or you might need to wait for a SteamOS patch that fixes the issue.

Hopefully you can get things working!

**Comment by beatc1234** [comment]
Finally got it working using bottles. Thx for the help!
