### ISSUE TITLE
Great guide!

### ISSUE THREAD

**Issue by smee2018** [oh-nyoo/steam-deck-advance#3]
thank you for the guide - it's the only one that works 100% of the time :)

Is it possible to put the commands into a script (SH?) to click and run in one go? I've tried but have almost zero Linux ability :(

**Comment by oh-nyoo** [comment]
Thanks for your comment. Unfortunately SteamOS is updated pretty regularly and I am not willing to make sure things continue to work between updates. A script would be even harder to maintain than just some notes, so until SteamOS becomes more stable, I wouldn't expect any scripts here
